/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vision;

import controle.EscreverArquivo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Felipe
 */
public class IFuncionario extends javax.swing.JFrame {

    EscreverArquivo escreverArquivo = new EscreverArquivo();
    String local = "Funcionarios";

    /**
     * Creates new form TelaFuncionario
     */
    public IFuncionario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FuncionarioMenu = new javax.swing.JTabbedPane();
        Lista = new javax.swing.JPanel();
        Tabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        pesquisaCaixaFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deletarButton = new javax.swing.JButton();
        registrarButton2 = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        Registro = new javax.swing.JPanel();
        Dados = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        telefoneFixoCaixa = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        estadoCivilCampo = new javax.swing.JComboBox<>();
        caixaEmail = new javax.swing.JTextField();
        cpfCaixa = new javax.swing.JFormattedTextField();
        telefoneCelularCaixa = new javax.swing.JFormattedTextField();
        rgCaixa = new javax.swing.JFormattedTextField();
        tituloCaixa = new javax.swing.JTextField();
        dataNacimentoCaixa = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nomeCaixa = new javax.swing.JTextField();
        dataAdimissaoCampo = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resevistaCaixa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        limparButton = new javax.swing.JButton();
        registrarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        Cargo = new javax.swing.JPanel();
        cargoCaixa = new javax.swing.JTextField();
        salarioCaixa = new javax.swing.JTextField();
        idCaixa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        statusCampo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        campoDependentes = new javax.swing.JTextField();
        CargosDisponiveis = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cargoTable = new javax.swing.JTable();
        pesquisaCaixa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Editar = new javax.swing.JPanel();
        EditarDados = new javax.swing.JPanel();
        Dados1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        telefoneFixoCaixa1 = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        estadoCivilCampo1 = new javax.swing.JComboBox<>();
        caixaEmail1 = new javax.swing.JTextField();
        cpfCaixa1 = new javax.swing.JFormattedTextField();
        telefoneCelularCaixa1 = new javax.swing.JFormattedTextField();
        rgCaixa1 = new javax.swing.JFormattedTextField();
        tituloCaixa1 = new javax.swing.JTextField();
        dataNacimentoCaixa1 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nomeCaixa1 = new javax.swing.JTextField();
        dataAdimissaoCampo1 = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        resevistaCaixa1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        salvarButton = new javax.swing.JButton();
        cancelarButton2 = new javax.swing.JButton();
        Cargo1 = new javax.swing.JPanel();
        cargoCaixa1 = new javax.swing.JTextField();
        salarioCaixa1 = new javax.swing.JTextField();
        idCaixa1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        statusCampo1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        campoDependentes1 = new javax.swing.JTextField();
        avancadoChexBox = new javax.swing.JCheckBox();
        CargosDisponiveis1 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cargoTable1 = new javax.swing.JTable();
        pesquisaCaixa1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        FuncionarioMenu.setToolTipText("");

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG", "CPF", "Nº Titulo Eleitoral", "E-MAIL", "Telefone Fixo", "Telefone Celular", "Certficado de Resevista", "Data de Nascimento", "Data de Admissão", "Dependentes", "Estado Cívil", "Cargo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaFuncionario);
        if (tabelaFuncionario.getColumnModel().getColumnCount() > 0) {
            tabelaFuncionario.getColumnModel().getColumn(1).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(1).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(3).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(3).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(4).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(4).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(5).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(5).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(6).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(6).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(7).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(7).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(8).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(8).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(9).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(9).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(10).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(10).setMaxWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(11).setMinWidth(0);
            tabelaFuncionario.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        javax.swing.GroupLayout TabelaLayout = new javax.swing.GroupLayout(Tabela);
        Tabela.setLayout(TabelaLayout);
        TabelaLayout.setHorizontalGroup(
            TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        TabelaLayout.setVerticalGroup(
            TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pesquisaCaixaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaCaixaFuncionarioActionPerformed(evt);
            }
        });
        pesquisaCaixaFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaCaixaFuncionarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaCaixaFuncionarioKeyReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder_explore.png"))); // NOI18N

        deletarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_delete.png"))); // NOI18N
        deletarButton.setText("Excluir");
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        registrarButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_add.png"))); // NOI18N
        registrarButton2.setText("Incluir");
        registrarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButton2ActionPerformed(evt);
            }
        });

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_edit.png"))); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesquisaCaixaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(pesquisaCaixaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(3, 3, 3))
                        .addComponent(registrarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deletarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ListaLayout = new javax.swing.GroupLayout(Lista);
        Lista.setLayout(ListaLayout);
        ListaLayout.setHorizontalGroup(
            ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListaLayout.setVerticalGroup(
            ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FuncionarioMenu.addTab("Listar", Lista);

        Dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Funcionário"));

        jLabel7.setText("Estado Cívil");

        jLabel12.setText("Telefone Fixo");

        jLabel8.setText("Dependetes");

        try {
            telefoneFixoCaixa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("D. Nascimento");

        jLabel13.setText("E-MAIL");

        estadoCivilCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<  Estado Cívil >", "Solteiro", "Casado" }));
        estadoCivilCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilCampoActionPerformed(evt);
            }
        });

        try {
            cpfCaixa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneCelularCaixa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            rgCaixa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dataNacimentoCaixa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Título de Eleitor (Nº da Inscrição)");

        jLabel1.setText("Nome");

        jLabel14.setText("Telefone Celular");

        nomeCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCaixaActionPerformed(evt);
            }
        });

        try {
            dataAdimissaoCampo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("D. Admissão");

        jLabel3.setText("RG");

        jLabel5.setText("CPF");

        jLabel6.setText("Certificado de Resevista (Nº do RA) ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        limparButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CleanMyMac-1-icon.png"))); // NOI18N
        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        registrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_add.png"))); // NOI18N
        registrarButton.setText("Incluir");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Cargo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ocupação"));

        jLabel11.setText("Cargo");

        jLabel17.setText("Salario");

        jLabel18.setText("Identificação");

        javax.swing.GroupLayout CargoLayout = new javax.swing.GroupLayout(Cargo);
        Cargo.setLayout(CargoLayout);
        CargoLayout.setHorizontalGroup(
            CargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CargoLayout.setVerticalGroup(
            CargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargoLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addComponent(cargoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(salarioCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<  Status >", "Ativo", "Inativo", "Ferias" }));
        statusCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCampoActionPerformed(evt);
            }
        });

        jLabel19.setText("Status");

        javax.swing.GroupLayout DadosLayout = new javax.swing.GroupLayout(Dados);
        Dados.setLayout(DadosLayout);
        DadosLayout.setHorizontalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(185, 185, 185)
                                .addComponent(jLabel3)
                                .addGap(158, 158, 158)
                                .addComponent(jLabel5))
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel12)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel14))
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tituloCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneFixoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(telefoneCelularCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel19)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel10))
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(caixaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(statusCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dataAdimissaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addComponent(nomeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rgCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cpfCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosLayout.createSequentialGroup()
                                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DadosLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(23, 23, 23)
                                        .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(DadosLayout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(jLabel6))))
                                    .addGroup(DadosLayout.createSequentialGroup()
                                        .addComponent(dataNacimentoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(campoDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(resevistaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(estadoCivilCampo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(7, 7, 7))
        );
        DadosLayout.setVerticalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addGap(5, 5, 5)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rgCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel14)))
                .addGap(5, 5, 5)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneFixoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(telefoneCelularCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)))
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataNacimentoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resevistaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadoCivilCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataAdimissaoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DadosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        CargosDisponiveis.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargos Disponiveis"));

        cargoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cargo", "Salario", "Identificação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cargoTable.setColumnSelectionAllowed(true);
        cargoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cargoTable);
        cargoTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        pesquisaCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaCaixaActionPerformed(evt);
            }
        });
        pesquisaCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaCaixaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaCaixaKeyReleased(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder_explore.png"))); // NOI18N

        javax.swing.GroupLayout CargosDisponiveisLayout = new javax.swing.GroupLayout(CargosDisponiveis);
        CargosDisponiveis.setLayout(CargosDisponiveisLayout);
        CargosDisponiveisLayout.setHorizontalGroup(
            CargosDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargosDisponiveisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CargosDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CargosDisponiveisLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        CargosDisponiveisLayout.setVerticalGroup(
            CargosDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargosDisponiveisLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargosDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro);
        Registro.setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CargosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CargosDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FuncionarioMenu.addTab("", Registro);

        javax.swing.GroupLayout EditarDadosLayout = new javax.swing.GroupLayout(EditarDados);
        EditarDados.setLayout(EditarDadosLayout);
        EditarDadosLayout.setHorizontalGroup(
            EditarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EditarDadosLayout.setVerticalGroup(
            EditarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Dados1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Funcionário"));

        jLabel15.setText("Estado Cívil");

        jLabel20.setText("Telefone Fixo");

        jLabel21.setText("Dependetes");

        try {
            telefoneFixoCaixa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel22.setText("D. Nascimento");

        jLabel23.setText("E-MAIL");

        estadoCivilCampo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<  Estado Cívil >", "Solteiro", "Casado" }));
        estadoCivilCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilCampo1ActionPerformed(evt);
            }
        });

        try {
            cpfCaixa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneCelularCaixa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            rgCaixa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dataNacimentoCaixa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel24.setText("Título de Eleitor (Nº da Inscrição)");

        jLabel25.setText("Nome");

        jLabel26.setText("Telefone Celular");

        nomeCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCaixa1ActionPerformed(evt);
            }
        });

        try {
            dataAdimissaoCampo1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel27.setText("D. Admissão");

        jLabel28.setText("RG");

        jLabel29.setText("CPF");

        jLabel30.setText("Certificado de Resevista (Nº do RA) ");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        salvarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelarButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        cancelarButton2.setText("Cancelar");
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Cargo1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ocupação"));

        jLabel31.setText("Cargo");

        jLabel32.setText("Salario");

        jLabel33.setText("Identificação");

        javax.swing.GroupLayout Cargo1Layout = new javax.swing.GroupLayout(Cargo1);
        Cargo1.setLayout(Cargo1Layout);
        Cargo1Layout.setHorizontalGroup(
            Cargo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cargo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cargo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Cargo1Layout.setVerticalGroup(
            Cargo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cargo1Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(1, 1, 1)
                .addComponent(cargoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addGap(1, 1, 1)
                .addComponent(salarioCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusCampo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<  Status >", "Ativo", "Inativo", "De Ferias" }));
        statusCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCampo1ActionPerformed(evt);
            }
        });

        jLabel34.setText("Status");

        avancadoChexBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avancadoChexBox.setForeground(new java.awt.Color(255, 0, 0));
        avancadoChexBox.setText("Modo Avançado");
        avancadoChexBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancadoChexBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dados1Layout = new javax.swing.GroupLayout(Dados1);
        Dados1.setLayout(Dados1Layout);
        Dados1Layout.setHorizontalGroup(
            Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dados1Layout.createSequentialGroup()
                        .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(tituloCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dados1Layout.createSequentialGroup()
                                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(telefoneFixoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dados1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(0, 79, Short.MAX_VALUE))
                                    .addComponent(telefoneCelularCaixa1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dados1Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rgCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGap(29, 29, 29)
                                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(cpfCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Dados1Layout.createSequentialGroup()
                        .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(dataNacimentoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dados1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(Dados1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dados1Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27)
                                        .addGap(108, 108, 108))
                                    .addGroup(Dados1Layout.createSequentialGroup()
                                        .addComponent(statusCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dataAdimissaoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Dados1Layout.createSequentialGroup()
                                    .addComponent(resevistaCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(estadoCivilCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(3, 3, 3))
                    .addGroup(Dados1Layout.createSequentialGroup()
                        .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Dados1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(23, 23, 23)
                                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDependentes1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Dados1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Cargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dados1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(avancadoChexBox)))
                .addContainerGap())
        );
        Dados1Layout.setVerticalGroup(
            Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dados1Layout.createSequentialGroup()
                .addComponent(avancadoChexBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneFixoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneCelularCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel30)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22))
                .addGap(4, 4, 4)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resevistaCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDependentes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNacimentoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixaEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataAdimissaoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dados1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        CargosDisponiveis1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargos Disponiveis"));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder_explore.png"))); // NOI18N

        cargoTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cargo", "Salario", "Identificação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cargoTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargoTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cargoTable1MouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(cargoTable1);
        cargoTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        pesquisaCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaCaixa1ActionPerformed(evt);
            }
        });
        pesquisaCaixa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaCaixa1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaCaixa1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout CargosDisponiveis1Layout = new javax.swing.GroupLayout(CargosDisponiveis1);
        CargosDisponiveis1.setLayout(CargosDisponiveis1Layout);
        CargosDisponiveis1Layout.setHorizontalGroup(
            CargosDisponiveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargosDisponiveis1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CargosDisponiveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CargosDisponiveis1Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisaCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CargosDisponiveis1Layout.setVerticalGroup(
            CargosDisponiveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargosDisponiveis1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargosDisponiveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EditarLayout = new javax.swing.GroupLayout(Editar);
        Editar.setLayout(EditarLayout);
        EditarLayout.setHorizontalGroup(
            EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarLayout.createSequentialGroup()
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CargosDisponiveis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        EditarLayout.setVerticalGroup(
            EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Dados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CargosDisponiveis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(EditarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FuncionarioMenu.addTab("", Editar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FuncionarioMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FuncionarioMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void preencherTabelaCargo() throws IOException {
        DefaultTableModel cargos = (DefaultTableModel) cargoTable.getModel();
        String dadosCargo[];
        File arquivo = new File("Dados\\cargos");
        FileReader fr = new FileReader(arquivo);
        BufferedReader br = new BufferedReader(fr);
        String cargo = br.readLine();
        while (cargo != null) {
            dadosCargo = cargo.split(";");
            cargos.addRow(dadosCargo);
            cargo = br.readLine();
        }
        br.close();
        fr.close();
    }

    public void preencherTabelaFuncionario() throws IOException {
        DefaultTableModel funcionario = (DefaultTableModel) tabelaFuncionario.getModel();
        String dadosFuncionario[];
        File arquivo = new File("Dados\\funcionarios");
        FileReader fr = new FileReader(arquivo);
        BufferedReader br = new BufferedReader(fr);
        String linha = br.readLine();
        while (linha != null) {
            dadosFuncionario = linha.split(";");
            funcionario.addRow(dadosFuncionario);
            linha = br.readLine();
        }
        br.close();
        fr.close();

    }

    public void preencherTabelaCargoEditar() throws IOException {
        DefaultTableModel cargos = (DefaultTableModel) cargoTable1.getModel();
        String dadosCargo[];
        File arquivo = new File("Dados\\cargos");
        FileReader fr = new FileReader(arquivo);
        BufferedReader br = new BufferedReader(fr);
        String cargo = br.readLine();
        while (cargo != null) {
            dadosCargo = cargo.split(";");
            cargos.addRow(dadosCargo);
            cargo = br.readLine();
        }
        br.close();
        fr.close();
    }

    void bloquear() {
        cargoCaixa.setEditable(false);
        salarioCaixa.setEditable(false);
        idCaixa.setEditable(false);
        cargoCaixa1.setEditable(false);
        salarioCaixa1.setEditable(false);
        idCaixa1.setEditable(false);
        nomeCaixa1.setEditable(false);
        rgCaixa1.setEditable(false);
        cpfCaixa1.setEditable(false);
        tituloCaixa1.setEditable(false);
        dataNacimentoCaixa1.setEditable(false);
        resevistaCaixa1.setEditable(false);
        cargoCaixa.setBackground(new java.awt.Color(204, 204, 204));
        salarioCaixa.setBackground(new java.awt.Color(204, 204, 204));
        idCaixa.setBackground(new java.awt.Color(204, 204, 204));
        cargoCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        salarioCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        idCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        rgCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        cpfCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        tituloCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        nomeCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        dataNacimentoCaixa1.setBackground(new java.awt.Color(204, 204, 204));
        resevistaCaixa1.setBackground(new java.awt.Color(204, 204, 204));

    }

    void desbloquear() {
        cargoCaixa.setEditable(true);
        salarioCaixa.setEditable(true);
        idCaixa.setEditable(true);
        //cargoCaixa1.setEditable(true);
        // salarioCaixa1.setEditable(true);
        // idCaixa1.setEditable(true);
        nomeCaixa1.setEditable(true);
        rgCaixa1.setEditable(true);
        cpfCaixa1.setEditable(true);
        tituloCaixa1.setEditable(true);
        dataNacimentoCaixa1.setEditable(true);
        resevistaCaixa1.setEditable(true);
        cargoCaixa.setBackground(new java.awt.Color(255, 255, 255));
        salarioCaixa.setBackground(new java.awt.Color(255, 255, 255));
        idCaixa.setBackground(new java.awt.Color(255, 255, 255));
        // cargoCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        // salarioCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        //idCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        rgCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        cpfCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        tituloCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        nomeCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        dataNacimentoCaixa1.setBackground(new java.awt.Color(255, 255, 255));
        resevistaCaixa1.setBackground(new java.awt.Color(255, 255, 255));

    }

    void limpar() {
        nomeCaixa1.setText("");
        rgCaixa1.setText("");
        cpfCaixa1.setText("");
        tituloCaixa1.setText("");
        caixaEmail1.setText("");
        telefoneFixoCaixa1.setText("");
        telefoneCelularCaixa1.setText("");
        resevistaCaixa1.setText("");
        dataNacimentoCaixa1.setText("");
        dataAdimissaoCampo1.setText("");
        campoDependentes1.setText("");
        nomeCaixa.setText("");
        rgCaixa.setText("");
        cpfCaixa.setText("");
        tituloCaixa.setText("");
        caixaEmail.setText("");
        telefoneFixoCaixa.setText("");
        telefoneCelularCaixa.setText("");
        resevistaCaixa.setText("");
        dataNacimentoCaixa.setText("");
        dataAdimissaoCampo.setText("");
        campoDependentes.setText("");
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            preencherTabelaFuncionario();
            preencherTabelaCargo();
            preencherTabelaCargoEditar();
            FuncionarioMenu.setEnabledAt(2, false);
            FuncionarioMenu.setEnabledAt(1, false);

        } catch (IOException ex) {
            Logger.getLogger(IFuncionario.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        bloquear();
    }//GEN-LAST:event_formWindowOpened

    private void estadoCivilCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilCampoActionPerformed

    private void nomeCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCaixaActionPerformed


    private void statusCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCampoActionPerformed
    void filtrar() {
        TableRowSorter sorter = null;
        DefaultTableModel cargos = (DefaultTableModel) cargoTable.getModel();
        sorter = new TableRowSorter(cargos);
        cargoTable.setRowSorter(sorter);
        String text = pesquisaCaixa.getText();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter(text));
            } catch (Exception ex) {
            }
        }
    }
    private void cargoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoTableMouseClicked
        // TODO add your handling code here:
        int aux = cargoTable.getSelectedRow();
        cargoCaixa.setText((String) cargoTable.getValueAt(aux, 0));
        salarioCaixa.setText((String) cargoTable.getValueAt(aux, 1));
        idCaixa.setText((String) cargoTable.getValueAt(aux, 2));
    }//GEN-LAST:event_cargoTableMouseClicked

    private void pesquisaCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixaActionPerformed

    void deletar() {
        DefaultTableModel funcionario = (DefaultTableModel) tabelaFuncionario.getModel();
        if (tabelaFuncionario.getSelectedRow() >= 0) {
            funcionario.removeRow(tabelaFuncionario.getSelectedRow());
            tabelaFuncionario.setModel(funcionario);
            try {
                escreverArquivo.salvar(funcionario, local);
            } catch (IOException ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
    }
    private void pesquisaCaixaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaCaixaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixaKeyPressed

    private void pesquisaCaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaCaixaKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_pesquisaCaixaKeyReleased

    private void pesquisaCaixaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaCaixaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixaFuncionarioActionPerformed

    private void pesquisaCaixaFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaCaixaFuncionarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixaFuncionarioKeyPressed

    private void pesquisaCaixaFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaCaixaFuncionarioKeyReleased
        // TODO add your handling code here:
        filtrarFuncionario();
    }//GEN-LAST:event_pesquisaCaixaFuncionarioKeyReleased

    private void estadoCivilCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilCampo1ActionPerformed

    private void nomeCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCaixa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCaixa1ActionPerformed

    private void statusCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCampo1ActionPerformed

    private void cargoTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoTable1MouseClicked
        // TODO add your handling code here:
        int aux = cargoTable1.getSelectedRow();
        cargoCaixa1.setText((String) cargoTable1.getValueAt(aux, 0));
        salarioCaixa1.setText((String) cargoTable1.getValueAt(aux, 1));
        idCaixa1.setText((String) cargoTable1.getValueAt(aux, 2));
    }//GEN-LAST:event_cargoTable1MouseClicked

    private void pesquisaCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaCaixa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixa1ActionPerformed

    private void pesquisaCaixa1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaCaixa1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixa1KeyPressed

    private void pesquisaCaixa1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaCaixa1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaCaixa1KeyReleased

    private void tabelaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionarioMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaFuncionarioMouseClicked

    private void cargoTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoTable1MouseEntered

    private void avancadoChexBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancadoChexBoxActionPerformed
        if (avancadoChexBox.isSelected()) {
            desbloquear();
        } else {
            bloquear();
        }

    }//GEN-LAST:event_avancadoChexBoxActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        if (rgCaixa1.getText() == null || nomeCaixa1.getText() == null || cpfCaixa1.getText() == null
                || tituloCaixa1.getText() == null || telefoneFixoCaixa1.getText() == null || telefoneCelularCaixa1.getText() == null
                || telefoneCelularCaixa1.getText() == null || telefoneCelularCaixa1.getText() == null || resevistaCaixa1.getText() == null
                || dataNacimentoCaixa1.getText() == null || campoDependentes1.getText() == null || ("" + estadoCivilCampo1.getSelectedItem()).equalsIgnoreCase("<  Estado Cívil >")
                || caixaEmail1.getText() == null || ("" + statusCampo1.getSelectedItem()).equalsIgnoreCase("<  Status >")
                || dataAdimissaoCampo1.getText() == null) {
            JOptionPane.showMessageDialog(null, "Favor preencha todos os campos");

        } else {
            deletar();
            DefaultTableModel funcionario = (DefaultTableModel) tabelaFuncionario.getModel();
            funcionario.addRow(new String[]{nomeCaixa1.getText(), rgCaixa1.getText(), cpfCaixa1.getText(), tituloCaixa1.getText(),
                caixaEmail1.getText(), telefoneFixoCaixa1.getText(), telefoneCelularCaixa1.getText(), resevistaCaixa1.getText(), dataNacimentoCaixa1.getText(),
                dataAdimissaoCampo1.getText(), campoDependentes1.getText(), estadoCivilCampo1.getSelectedItem() + "", idCaixa1.getText(), statusCampo1.getSelectedItem() + ""});
            try {

                escreverArquivo.salvar(funcionario, local);
                JOptionPane.showMessageDialog(null, "Funcionario Editado Com Sucesso");
                limpar();
                FuncionarioMenu.setSelectedIndex(0);
                bloquear();

            } catch (IOException ex) {
                Logger.getLogger(IFuncionario.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_salvarButtonActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed
        // TODO add your handling code here:
        FuncionarioMenu.setEnabledAt(0, true);
        FuncionarioMenu.setSelectedIndex(0);
        FuncionarioMenu.setEnabledAt(2, false);
        limpar();
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_limparButtonActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed

        DefaultTableModel funcionario = (DefaultTableModel) tabelaFuncionario.getModel();
        funcionario.addRow(new String[]{nomeCaixa.getText(), rgCaixa.getText(), cpfCaixa.getText(), tituloCaixa.getText(),
            caixaEmail.getText(), telefoneFixoCaixa.getText(), telefoneCelularCaixa.getText(), resevistaCaixa.getText(), dataNacimentoCaixa.getText(),
            dataAdimissaoCampo.getText(), campoDependentes.getText(), estadoCivilCampo.getSelectedItem() + "", idCaixa.getText(), statusCampo.getSelectedItem() + ""});
        try {
            escreverArquivo.salvar(funcionario, local);
            JOptionPane.showMessageDialog(null, "Funcionario Registrado");
            limpar();

        } catch (IOException ex) {
            Logger.getLogger(IFuncionario.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        FuncionarioMenu.setSelectedIndex(0);
        FuncionarioMenu.setEnabledAt(0, true);
        FuncionarioMenu.setEnabledAt(1, false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        deletar();
    }//GEN-LAST:event_deletarButtonActionPerformed

    private void registrarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButton2ActionPerformed
        FuncionarioMenu.setSelectedIndex(1);
        if (avancadoChexBox.isSelected()) {
            desbloquear();
        } else {
            bloquear();
        }
    }//GEN-LAST:event_registrarButton2ActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        if (tabelaFuncionario.getSelectedRow() >= 0) {
            FuncionarioMenu.setEnabledAt(0, false);
            FuncionarioMenu.setSelectedIndex(2);
            int aux = tabelaFuncionario.getSelectedRow();
            nomeCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 0));
            rgCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 1));
            cpfCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 2));
            tituloCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 3));
            caixaEmail1.setText((String) tabelaFuncionario.getValueAt(aux, 4));
            telefoneFixoCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 5));
            telefoneCelularCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 6));
            resevistaCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 7));
            dataNacimentoCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 8));
            dataAdimissaoCampo1.setText((String) tabelaFuncionario.getValueAt(aux, 9));
            campoDependentes1.setText((String) tabelaFuncionario.getValueAt(aux, 10));
            String estado = (String) tabelaFuncionario.getValueAt(aux, 11);
            if (estado.equalsIgnoreCase("solteiro")) {
                estadoCivilCampo1.setSelectedIndex(1);
            } else {
                estadoCivilCampo1.setSelectedIndex(2);
            }

            idCaixa1.setText((String) tabelaFuncionario.getValueAt(aux, 12));
            String status = (String) tabelaFuncionario.getValueAt(aux, 13);
            if (status.equalsIgnoreCase("Ativo")) {
                statusCampo1.setSelectedIndex(1);
            } else {
                if (status.equalsIgnoreCase("Inativo")) {
                    statusCampo1.setSelectedIndex(2);
                } else {
                    statusCampo1.setSelectedIndex(3);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");

        }

    }//GEN-LAST:event_editarButtonActionPerformed
    void filtrarFuncionario() {
        TableRowSorter sorter = null;
        DefaultTableModel funcionarios = (DefaultTableModel) tabelaFuncionario.getModel();
        sorter = new TableRowSorter(funcionarios);
        tabelaFuncionario.setRowSorter(sorter);
        String text = pesquisaCaixaFuncionario.getText();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter(text));
            } catch (Exception ex) {
            }
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cargo;
    private javax.swing.JPanel Cargo1;
    private javax.swing.JPanel CargosDisponiveis;
    private javax.swing.JPanel CargosDisponiveis1;
    private javax.swing.JPanel Dados;
    private javax.swing.JPanel Dados1;
    private javax.swing.JPanel Editar;
    private javax.swing.JPanel EditarDados;
    private javax.swing.JTabbedPane FuncionarioMenu;
    private javax.swing.JPanel Lista;
    private javax.swing.JPanel Registro;
    private javax.swing.JPanel Tabela;
    private javax.swing.JCheckBox avancadoChexBox;
    private javax.swing.JTextField caixaEmail;
    private javax.swing.JTextField caixaEmail1;
    private javax.swing.JTextField campoDependentes;
    private javax.swing.JTextField campoDependentes1;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarButton2;
    private javax.swing.JTextField cargoCaixa;
    private javax.swing.JTextField cargoCaixa1;
    private javax.swing.JTable cargoTable;
    private javax.swing.JTable cargoTable1;
    private javax.swing.JFormattedTextField cpfCaixa;
    private javax.swing.JFormattedTextField cpfCaixa1;
    private javax.swing.JFormattedTextField dataAdimissaoCampo;
    private javax.swing.JFormattedTextField dataAdimissaoCampo1;
    private javax.swing.JFormattedTextField dataNacimentoCaixa;
    private javax.swing.JFormattedTextField dataNacimentoCaixa1;
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JComboBox<String> estadoCivilCampo;
    private javax.swing.JComboBox<String> estadoCivilCampo1;
    private javax.swing.JTextField idCaixa;
    private javax.swing.JTextField idCaixa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limparButton;
    private javax.swing.JTextField nomeCaixa;
    private javax.swing.JTextField nomeCaixa1;
    private javax.swing.JTextField pesquisaCaixa;
    private javax.swing.JTextField pesquisaCaixa1;
    private javax.swing.JTextField pesquisaCaixaFuncionario;
    private javax.swing.JButton registrarButton;
    private javax.swing.JButton registrarButton2;
    private javax.swing.JTextField resevistaCaixa;
    private javax.swing.JTextField resevistaCaixa1;
    private javax.swing.JFormattedTextField rgCaixa;
    private javax.swing.JFormattedTextField rgCaixa1;
    private javax.swing.JTextField salarioCaixa;
    private javax.swing.JTextField salarioCaixa1;
    private javax.swing.JButton salvarButton;
    private javax.swing.JComboBox<String> statusCampo;
    private javax.swing.JComboBox<String> statusCampo1;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JFormattedTextField telefoneCelularCaixa;
    private javax.swing.JFormattedTextField telefoneCelularCaixa1;
    private javax.swing.JFormattedTextField telefoneFixoCaixa;
    private javax.swing.JFormattedTextField telefoneFixoCaixa1;
    private javax.swing.JTextField tituloCaixa;
    private javax.swing.JTextField tituloCaixa1;
    // End of variables declaration//GEN-END:variables
}
