/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vision;

import controle.CalculosGerais;
import controle.DataHora;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Felipe
 */
public final class Iprincipal extends javax.swing.JFrame {

    DataHora dataHora = new DataHora();
    CalculosGerais calculosGerais = new CalculosGerais();

    /**
     * Creates new form Iprincipal
     */
    public Iprincipal() throws IOException {
        initComponents();
        loopDataHora();
        estimativas();
        loopEstimativas();
    }

    void estimativas() throws IOException {
        quantFuncionarios.setText("" + calculosGerais.quant("funcionarios"));
        quantCargos.setText("" + calculosGerais.quant("cargos"));
        //estimativaMes.setText(""+calculosGerais.estimativaSaida());
    }

    void loopDataHora() {
        new Thread() {
            @Override
            public void run() {
                for (;;) {
                    jHora.setText(dataHora.setHora());
                    jData.setText(dataHora.setData());
                    try {
                        sleep(1000);
                    } catch (InterruptedException ie) {

                    }
                }
            }
        }.start();
    }

    void loopEstimativas() {
        new Thread() {
            @Override
            public void run() {
                for (;;) {
                    try {
                        estimativas();
                    } catch (IOException ex) {
                        Logger.getLogger(Iprincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        sleep(10000);
                    } catch (InterruptedException ie) {

                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPPrincipal = new javax.swing.JPanel();
        jHora = new javax.swing.JLabel();
        jData = new javax.swing.JLabel();
        JpEstimativas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quantFuncionarios = new javax.swing.JTextField();
        quantCargos = new javax.swing.JTextField();
        estimativaMes = new javax.swing.JTextField();
        barraMenu = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        Importar = new javax.swing.JMenuItem();
        Exportar = new javax.swing.JMenuItem();
        arquivoEmpresa = new javax.swing.JMenuItem();
        funcionarioMenu = new javax.swing.JMenu();
        menuGerenciarFuncionarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        cargosMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenu = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pagamento de Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jHora.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock.png"))); // NOI18N

        jData.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/date.png"))); // NOI18N

        jLabel3.setText("Estimativa de Saida:");

        jLabel2.setText("Quantidade de Cargos:");

        jLabel1.setText("Quantidade de Funcionarios:");

        quantFuncionarios.setEditable(false);
        quantFuncionarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        quantCargos.setEditable(false);
        quantCargos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        estimativaMes.setEditable(false);
        estimativaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout JpEstimativasLayout = new javax.swing.GroupLayout(JpEstimativas);
        JpEstimativas.setLayout(JpEstimativasLayout);
        JpEstimativasLayout.setHorizontalGroup(
            JpEstimativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpEstimativasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpEstimativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JpEstimativasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantFuncionarios))
                    .addGroup(JpEstimativasLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantCargos))
                    .addGroup(JpEstimativasLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estimativaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JpEstimativasLayout.setVerticalGroup(
            JpEstimativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEstimativasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpEstimativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quantFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpEstimativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(quantCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpEstimativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estimativaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jHora)
                .addGap(18, 18, 18)
                .addComponent(jData)
                .addContainerGap())
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpEstimativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpEstimativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jHora)
                    .addComponent(jData))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        barraMenu.setMinimumSize(new java.awt.Dimension(0, 4));

        arquivoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder.png"))); // NOI18N
        arquivoMenu.setText("Arquivos");

        Importar.setText("Importar Dados");
        Importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarActionPerformed(evt);
            }
        });
        arquivoMenu.add(Importar);

        Exportar.setText("Exportar Dados");
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });
        arquivoMenu.add(Exportar);

        arquivoEmpresa.setText("Empresa");
        arquivoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoEmpresaActionPerformed(evt);
            }
        });
        arquivoMenu.add(arquivoEmpresa);

        barraMenu.add(arquivoMenu);

        funcionarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/group.png"))); // NOI18N
        funcionarioMenu.setText("Funcionários");

        menuGerenciarFuncionarios.setText("Gerenciar");
        menuGerenciarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarFuncionariosActionPerformed(evt);
            }
        });
        funcionarioMenu.add(menuGerenciarFuncionarios);

        jMenuItem2.setText("Pagamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        funcionarioMenu.add(jMenuItem2);

        barraMenu.add(funcionarioMenu);

        cargosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tag_blue.png"))); // NOI18N
        cargosMenu.setText("Cargos");

        jMenuItem1.setText("Gerenciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        cargosMenu.add(jMenuItem1);

        barraMenu.add(cargosMenu);

        ajudaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        ajudaMenu.setText("Ajuda");
        barraMenu.add(ajudaMenu);

        sobreMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/information.png"))); // NOI18N
        sobreMenu.setText("Sobre");
        barraMenu.add(sobreMenu);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        sair.setText("Sair");
        barraMenu.add(sair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(812, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Escolha o Diretorio");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.showOpenDialog(barraMenu);

        String caminho = jFileChooser.getSelectedFile().getAbsolutePath();
        new File("Dados").mkdirs();
        String cargos = caminho + "\\cargos";
        try {
            copiar(caminho + "\\cargos", "Dados\\cargos");
            copiar(caminho + "\\empresa", "Dados\\empresa");
            copiar(caminho + "\\funcionarios", "Dados\\funcionarios");
            JOptionPane.showMessageDialog(null, "Dados Importados com Sucesso");
        } catch (IOException ex) {
            Logger.getLogger(Iprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ImportarActionPerformed
    void copiar(String de, String para) throws FileNotFoundException, IOException {
        //File dee = new File(de);

        FileReader fr = new FileReader(de);
        BufferedReader br = new BufferedReader(fr);
        // File paraa = new File(para);
        FileWriter fw = new FileWriter(para);
        BufferedWriter bw = new BufferedWriter(fw);

        String linha = br.readLine();
        while (linha != null) {
            bw.write(linha);
            linha = br.readLine();
        }
        bw.flush();
        bw.close();
        br.close();
        fr.close();
    }
    private void menuGerenciarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarFuncionariosActionPerformed
        // TODO add your handling code here:
        new IFuncionario().setVisible(true);
    }//GEN-LAST:event_menuGerenciarFuncionariosActionPerformed

    private void arquivoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoEmpresaActionPerformed
    
       new IEmpresa().setVisible(true);
    }//GEN-LAST:event_arquivoEmpresaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            new ICargo().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Iprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Escolha o Diretorio");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.showOpenDialog(barraMenu);
        String caminho = jFileChooser.getSelectedFile().getAbsolutePath();
        String aux = JOptionPane.showInputDialog(null, "Digite um nome");       

        new File(caminho + "\\" + aux).mkdirs();
        try {
            copiar("Dados\\cargos", caminho + "\\" + aux + "\\cargos");
            copiar("Dados\\empresa", caminho + "\\" + aux + "\\empresa");
            copiar("Dados\\funcionarios", caminho + "\\" + aux + "\\funcionarios");
            JOptionPane.showMessageDialog(null, "Dados Exportados com Sucesso");
        } catch (IOException ex) {
            Logger.getLogger(Iprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ExportarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            new IPagamento().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Iprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exportar;
    private javax.swing.JMenuItem Importar;
    private javax.swing.JPanel JpEstimativas;
    private javax.swing.JPanel Principal;
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JMenuItem arquivoEmpresa;
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu cargosMenu;
    private javax.swing.JTextField estimativaMes;
    private javax.swing.JMenu funcionarioMenu;
    private javax.swing.JLabel jData;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JMenuItem menuGerenciarFuncionarios;
    private javax.swing.JTextField quantCargos;
    private javax.swing.JTextField quantFuncionarios;
    private javax.swing.JMenu sair;
    private javax.swing.JMenu sobreMenu;
    // End of variables declaration//GEN-END:variables
}
